[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"

opacity = 1.0
blur = true

startup_mode = "Maximized"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 10

